apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: payal
      image: swagatdevops/hello:latest
      imagePullPolicy: Always
      ports: 
        - containerPort: 8080